name: Deploy WordPress to Lightsail by Azhaganandhan

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Files
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            . ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/home/${{ secrets.LIGHTSAIL_USER }}/wordpress-app

      - name: Run Docker Compose
        run: |
          ssh ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
          cd /home/${{ secrets.LIGHTSAIL_USER }}/wordpress-app
          docker-compose down
          docker-compose up -d --build
          EOF
